lib/shortener_web/router.ex
defmodule ShortenerWeb.Router do
  use ShortenerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ShortenerWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  scope "/", ShortenerWeb do
    pipe_through :browser

    get "/stats", StatsController, :index
    get "/stats.csv", StatsController, :csv

    resources "/", URLShortenerController, only: [:index, :create, :show], param: "slug"
    resources "/shortened", ShortenedController, only: [:show], param: "slug"
  end
end

lib/shortener_web/controllers/shortened_controller.ex
defmodule ShortenerWeb.ShortenedController do
  use ShortenerWeb, :controller
  alias Shortener.ShortenedURLs

  def show(conn, %{"slug" => slug}) do
    case ShortenedURLs.find(slug) do
      {:ok, shortened_url} ->
        render(conn, "show.html", shortened_url: shortened_url)

      {:error, :not_found} ->
        conn
        |> put_flash(:error, "Unable to find shortened url for '#{slug}' slug")
        |> redirect(to: Routes.url_shortener_path(conn, :index))
    end
  end
end

lib/shortener_web/views/shortened_view.ex
defmodule ShortenerWeb.ShortenedView do
  use ShortenerWeb, :view
end

lib/shortener_web/templates/shortened/show.html.heex
<div class="columns">
  <div class="column left">
    <%= render ShortenerWeb.LayoutView, "_shortz.html", conn: @conn %>
  </div>
  <div class="column right is-flex is-flex-direction-column is-justify-content-center">
    <div class="message is-primary">
      <div class="message-header">
        <p>Successfully shortened URL</p>
      </div>
      <div class="message-body is-flex is-justify-content-space-between is-align-items-center">
        <% url = Routes.url_shortener_url(@conn, :show, @shortened_url.slug) %>
        <p>
          Your Shortened URL is: <%= link url, to: url, class: "shortened-url" %>
        </p>
        <%= content_tag :button, "Copy", class: "js-clipboard-copy button", data: [clipboard_text: url] %>
      </div>
    </div>
    <%= link "Shorten another one!", to: Routes.url_shortener_path(@conn, :index), class: "button is-light is-align-self-flex-start" %>
  </div>
</div>