lib/shortener_web/router.ex
defmodule ShortenerWeb.Router do
  use ShortenerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ShortenerWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  scope "/", ShortenerWeb do
    pipe_through :browser

    get "/stats", StatsController, :index
    get "/stats.csv", StatsController, :csv

    resources "/", URLShortenerController, only: [:index, :create, :show], param: "slug"
    resources "/shortened", ShortenedController, only: [:show], param: "slug"
  end
end

lib/shortener_web/controllers/stats_controller.ex
defmodule ShortenerWeb.StatsController do
  use ShortenerWeb, :controller
  alias Shortener.ShortenedURLs

  plug :limit_params

  def index(conn, params) do
    page = ShortenedURLs.paginated_list(params)

    render(conn, "index.html",
      shortened_urls: page.entries,
      current_page: page.page_number,
      page_size: page.page_size,
      total_pages: page.total_pages,
      total_entries: page.total_entries
    )
  end

  def csv(conn, params) do
    page = ShortenedURLs.paginated_list(params)

    conn
    |> put_resp_content_type("text/csv")
    |> put_resp_header("content-disposition", "attachment; filename=\"stats.csv\"")
    |> put_root_layout(false)
    |> render("index.csv", shortened_urls: page.entries)
  end

  @allowed_pagination_params ["page"]
  defp limit_params(conn, _) do
    Map.put(conn, :params, Map.take(conn.params, @allowed_pagination_params))
  end
end

lib/shortener_web/views/stats_view.ex
defmodule ShortenerWeb.StatsView do
  use ShortenerWeb, :view
  alias Shortener.ShortenedURLs.ShortenedURL
  alias ShortenerWeb.Router.Helpers, as: Routes

  @fields_to_encode_csv [:shortened_url, :url, :page_views]

  def render("index.csv", assigns) do
    assigns[:shortened_urls]
    |> Enum.map(fn shortened_url ->
      shortened_url
      |> Map.put(:shortened_url, shortened_url_for(shortened_url))
      |> Map.take(@fields_to_encode_csv)
    end)
    |> CSV.encode(headers: @fields_to_encode_csv)
    |> Enum.to_list()
    |> to_string()
  end

  defp shortened_url_for(%ShortenedURL{slug: slug}) do
    Routes.url_shortener_url(ShortenerWeb.Endpoint, :show, slug)
  end
end

lib/shortener_web/templates/stats/index.html.heex
<%= if @shortened_urls == [] do %>
  <article class="message is-warning">
    <div class="message-body">
      Ohh! Looks like you have not shortened any URLs yet. <br><br>
      <%= link "Shorten now!", to: Routes.url_shortener_path(@conn, :index) %>
    </div>
  </article>
<% else %>
  <div class="is-flex is-justify-content-space-between">
    <div class="tabs">
      <ul>
        <li class="is-active"><a>Analytics Stats</a></li>
      </ul>
    </div>
    <div>
      <%= link "Back to URL Shortener", to: Routes.url_shortener_path(@conn, :index), class: "button is-light is-align-self-flex-start" %>
      <%= link "Download CSV", to: Routes.stats_path(@conn, :csv, page: @current_page), class: "button is-info is-light" %>
    </div>
  </div>
  <div class="table-container">
    <table class="table is-fullwidth">
      <thead>
        <tr>
          <th class="shortened-url-column">Shortened URL</th>
          <th>URL</th>
          <th class="page-views-column">Page Views</th>
        </tr>
      </thead>
      <tbody>
        <%= for shortened_url <- @shortened_urls do %>
          <tr>
            <% url = Routes.url_shortener_url(@conn, :show, shortened_url.slug) %>
            <td><%= link url, to: url %></td>
            <td class="full-url"><%= link shortened_url.url, to: shortened_url.url %></td>
            <td><%= shortened_url.page_views %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <nav class="pagination is-rounded is-right" role="navigation" aria-label="pagination">
    <ul class="pagination-list">
      <%= for page <- 1..@total_pages do %>
        <li>
          <% class = if page == @current_page, do: "pagination-link is-current", else: "pagination-link" %>
          <%= link page, to: Routes.stats_path(@conn, :index, page: page), class: class %>
        </li>
      <% end %>
    </ul>
  </nav>
<% end %>